export enum Phase {
  Init = 'Init',
  Preload = 'Preload',
  Splash = 'Splash',
  FreeRoundCampaign = 'FreeRoundCampaign',
  Idle = 'Idle',
  BuyFeatureIdle = 'BuyFeatureIdle',
  Spin = 'Spin',
  StopSpin = 'StopSpin',
  CloningWild = 'CloningWild',
  High2 = 'High2',
  Wild = 'Wild',
  WinLines = 'WinLines',
  WinShow = 'WinShow',
  MysteryFeature = 'MysteryFeature',
  MysterySpin = 'MysterySpin',
  MysteryFeatureChoose = 'MysteryFeatureChoose',
  FreeSpinIdle = 'FreeSpinIdle',
  FreeSpinSpin = 'FreeSpinSpin',
  FreeSpinBonusIdle = 'FreeSpinBonusIdle',
  FreeSpinBonusShot = 'FreeSpinBonusShot',
  EndGame = 'EndGame',
}
