
/**
 * Currency Code list provided by 1XBet on June 28 2023.
 * @author Dmitry Vasiliev
 * @link https://slots-broit.slack.com/archives/C040M2L31CP/p1687938911563399
 * 
 * DEMO currency is used as default when no currency is provided by server. It means that player doesn't use real money. 
*/
export enum CurrencyCode {
    DEMO = 'DEMO',
    AED = 'AED',
    ALL = 'ALL',
    AMD = 'AMD',
    AOA = 'AOA',
    ARS = 'ARS',
    AUD = 'AUD',
    AZN = 'AZN',
    BAM = 'BAM',
    BDT = 'BDT',
    BGN = 'BGN',
    BHD = 'BHD',
    BRL = 'BRL',
    BWP = 'BWP',
    BYN = 'BYN',
    CAD = 'CAD',
    CDF = 'CDF',
    CHF = 'CHF',
    CLP = 'CLP',
    CNY = 'CNY',
    COP = 'COP',
    CUP = 'CUP',
    CZK = 'CZK',
    DKK = 'DKK',
    EGP = 'EGP',
    ETB = 'ETB',
    EUR = 'EUR',
    // Отключено по согласованию с Dmitry Maksak https://slots-broit.slack.com/archives/C040M2L31CP/p1688980273394239?thread_ts=1687938911.563399&cid=C040M2L31CP
    // GBP = 'GBP', 
    GEL = 'GEL',
    GHS = 'GHS',
    GNF = 'GNF',
    GTQ = 'GTQ',
    HKD = 'HKD',
    HUF = 'HUF',
    IDR = 'IDR',
    INR = 'INR',
    IQD = 'IQD',
    IRR = 'IRR',
    ISK = 'ISK',
    JOD = 'JOD',
    JPY = 'JPY',
    KES = 'KES',
    KGS = 'KGS',
    KRW = 'KRW',
    KWD = 'KWD',
    KZT = 'KZT',
    LAK = 'LAK',
    LBP = 'LBP',
    LKR = 'LKR',
    LSL = 'LSL',
    LYD = 'LYD',
    MAD = 'MAD',
    MDL = 'MDL',
    MGA = 'MGA',
    MKD = 'MKD',
    MMK = 'MMK',
    MNT = 'MNT',
    MRU = 'MRU',
    MXN = 'MXN',
    MYR = 'MYR',
    MZN = 'MZN',
    NGN = 'NGN',
    NOK = 'NOK',
    NPR = 'NPR',
    NZD = 'NZD',
    OMR = 'OMR',
    PEN = 'PEN',
    PHP = 'PHP',
    PKR = 'PKR',
    PLN = 'PLN',
    PYG = 'PYG',
    QAR = 'QAR',
    RON = 'RON',
    RSD = 'RSD',
    RUB = 'RUB',
    SAR = 'SAR',
    SCR = 'SCR',
    SDG = 'SDG',
    SEK = 'SEK',
    SGD = 'SGD',
    THB = 'THB',
    TJS = 'TJS',
    TND = 'TND',
    TRY = 'TRY',
    TWD = 'TWD',
    TZS = 'TZS',
    UAH = 'UAH',
    UGX = 'UGX',
    USD = 'USD',
    UYU = 'UYU',
    UZS = 'UZS',
    VND = 'VND',
    XAF = 'XAF',
    XOF = 'XOF',
    ZAR = 'ZAR',
    ZMW = 'ZMW',
    ZWL = 'ZWL'
  }