// Route → OG metadata map.
//
// Pulled from DOCS_NAV (the authoritative source for the docs sidebar) plus
// a handful of top-level pages that don't appear there. Each entry produces
// a per-page OG image at /og/<route>.png.
//
// Pages not in this map fall back to the static og-default.png referenced
// in Base.astro.

import { DOCS_NAV } from '../content/nav';

export interface OGPage {
  title: string;
  description: string;
  eyebrow?: string;
}

const TOP_LEVEL: Record<string, OGPage> = {
  index: {
    title: 'slotplate',
    description: 'Opinionated slot-game client boilerplate. Server-authoritative, agent-ready, built on pixi-reels.',
    eyebrow: 'Slot game template',
  },
  changelog: {
    title: 'Changelog',
    description: 'Every release of create-slotplate, generated by Changesets.',
    eyebrow: 'Releases',
  },
  docs: {
    title: 'Docs',
    description: 'How slotplate fits together — concepts, principles, and the testing bridge.',
    eyebrow: 'Documentation',
  },
  architecture: {
    title: 'Architecture',
    description: 'The shape of slotplate — layers, FSM, spin lifecycle, event flow.',
    eyebrow: 'Architecture',
  },
  guides: {
    title: 'Guides',
    description: 'Add a symbol, a phase, a bonus game. Swap the network. Wire analytics.',
    eyebrow: 'How to',
  },
  patterns: {
    title: 'Patterns',
    description: 'The reusable patterns slotplate is built on — FSM, presenter, composition root.',
    eyebrow: 'Patterns',
  },
};

/** Strip leading + trailing slashes; turn an empty/root path into ''. */
function normalize(href: string): string {
  return href.replace(/^\//, '').replace(/\/$/, '');
}

// Description blurbs per nav section — used for sub-pages that aren't
// in TOP_LEVEL. Concise, ~10 words each, written like a sales tagline.
const SECTION_BLURB: Record<string, string> = {
  'Start here': 'How slotplate works and how to get going.',
  Architecture: 'How the layers fit together — FSM, phases, presenters.',
  Concepts: 'The mental model behind every slotplate decision.',
  Guides: 'Add features, swap services, extend the template.',
  Patterns: 'Reusable patterns slotplate is built on.',
};

export function buildOGPages(): Record<string, OGPage> {
  const out: Record<string, OGPage> = { ...TOP_LEVEL };
  for (const section of DOCS_NAV) {
    for (const item of section.items) {
      const key = normalize(item.href);
      if (out[key]) continue; // top-level wins
      out[key] = {
        eyebrow: section.title,
        title: item.label,
        description: SECTION_BLURB[section.title] ?? `One page in ${section.title}.`,
      };
    }
  }
  return out;
}

export const OG_PAGES = buildOGPages();
